### ISSUE TITLE
Move from intllib to Minetest 5.x client-side translation

### ISSUE THREAD

**Issue by Montandalar** [Marnack/advtrains_livery_tools#1]
I appreciate the effort to internationalise your mods, but `intllib` is not the latest best practice for doing so. `intllib` is considered a legacy library that predates the Minetest 5.x series' *client-side translation* features. This means that instead of the server setting the whole game's language, the clients can retrieve the locale files they want and displays strings in any localised language.

The transition should work easily because the intllib S() syntax is meant to be directly replaceable with the object one can get from a call to `minetest.get_translator`. See [the docs](https://github.com/minetest/minetest/blob/5.6.1/doc/lua_api.txt#L3653).

The AdvTrains project moved away from intllib thanks to Y. Wang in 2020 in commit cc78b63e3, in case you need a solid reference.

**Comment by Marnack** [comment]
I agree.  Unfortunately, it fell onto my list of items to address later in order to make a Beta release available sooner.  The minor complication that led me to that decision is that the livery template name is currently used as a key.  Thus, I need to review the code and will likely need to make some minor changes to where the translation occurs (i.e. at the point of display rather than when adding the template to the database).  It's not a big problem but it was another "just one more thing" type of issue that would have delayed the release further.  (I wanted to get some feedback on the mod before polishing everything to know if it would be worth the time.)  I'm quite glad that you brought it up here though so that I don't forget to address it.

Also, thanks for the tip about Y. Wang's change; that will be a very useful reference.

**Comment by Marnack** [comment]
Updated in release 0.8.3
